#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ISHApp.Droid.Resource", IsApplication=true)]

namespace ISHApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_actueel = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_beschikbaarheid = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_empty = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_historie = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_my_schedule = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_sessions = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_action_speakers = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_action_whats_on = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_launcher = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_launcher_tbi = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_tab_my_schedule = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_tab_sessions = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_tab_speakers = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_tab_whats_on = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int frameLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int listViewMeldingen = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int textView1 = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int message_list_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int simple_fragment = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int actueel_tab_label = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int beschikbaarheid_tab_label = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int historie_tab_label = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
